rectors:
    Rector\Rector\Contrib\PhpParser\IdentifierRector: ~
    Rector\Rector\Contrib\PhpParser\ParamAndStaticVarNameRector: ~

    Rector\Rector\Dynamic\ClassConstantReplacerRector:
        'PhpParser\Node\Stmt\Class_':
            'VISIBILITY_MODIFER_MASK': 'VISIBILITY_MODIFIER_MASK'
