rectors:
    Rector\Rector\Contrib\PhpParser\IdentifierRector: ~

    Rector\Rector\Dynamic\PropertyNameReplacerRector:
        'PhpParser\Node\Param':
            'name': 'var'

    Rector\Rector\Dynamic\ClassConstantReplacerRector:
        'PhpParser\Node\Stmt\Class_':
            'VISIBILITY_MODIFER_MASK': 'VISIBILITY_MODIFIER_MASK'
