language: php

php:
  - 7.1

install:
  - composer install
  # prepare nette/sandbox
  - composer create-project nette/sandbox:@dev temp/nette-sandbox

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
  # check coding standard (defined in composer.json "scripts" section)
  # if this fails, run "composer fix-cs" to fix all fixable issues
  - composer check-cs
  # check with phpstan (defined in composer.json "scripts" section)
  - composer phpstan
  # try on nette/sandbox
  - bin/rector process temp/nette-sandbox --config src/config/levels.yml

after_script:
  # upload coverage to Coveralls.io
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose

notifications:
  email: never
