language: php

php:
  - 7.2
  - 7.1

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit -v

stages:
  - coding standards
  - test
  - code coverage

jobs:
  include:
    - stage: coding standards
      php: 7.1
      script:
        - composer check-cs

    - stage: code coverage
      php: 7.1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
      script:
        - vendor/bin/phpunit --coverage-clover coverage.xml
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: never
