language: php

php:
  - 7.2
  - 7.1

before_install:
  # hide xdebug to speed up
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit -v

jobs:
  include:
    - stage: Coding Standards and Code Coverage
      php: 7.1
      script:
        - composer check-cs
    -
      php: 7.1
      script:
        # get xdebug back for coverage
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - vendor/bin/phpunit --coverage-clover coverage.xml
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml

notifications:
  email: never
