services:
    _defaults:
        autowire: true

    Rector\BetterReflection\:
        resource: '../../src'

    # Roave\BetterReflection
    Roave\BetterReflection\Reflector\ClassReflector:
        factory: ['@Rector\BetterReflection\Reflector\ClassReflectorFactory', 'create']

    # nikic\PHP-Parser
    Roave\BetterReflection\SourceLocator\Ast\Locator: ~
