rectors:
    Rector\Rector\Dynamic\ClassReplacerRector:
        'Environment': 'Nette\Environment'
        'Image': 'Nette\Image'
        'IRouter': '\Nette\Application\IRouter'
        'IHttpRequest': '\Nette\Http\IRequest'
        'PresenterRequest': '\Nette\Application\Request'
        'Presenter': '\Nette\Application\UI\Presenter'
    Rector\Rector\Contrib\Nette\Routing\BootstrapToRouterFactoryRector: ~
    Rector\Rector\Contrib\Nette\Routing\CleanupBootstrapToRouterFactoryRector: ~
