services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Rector\NodeTypeResolver\:
        resource: '../../src'

    PhpParser\NodeTraverser:
        calls:
            - ['addVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\TypeResolvingNodeVisitor']]
