services:
    _defaults:
        autowire: true

    Rector\NodeTypeResolver\:
        resource: '../../src'

    # PHPStan
#    PHPStan\Analyser\TypeSpecifier: ~
#    PHPStan\Analyser\NodeScopeResolver:
#        arguments:
#            $polluteScopeWithLoopInitialAssignments: false
#            $polluteCatchScopeWithTryAssignments: false
#            $earlyTerminatingMethodCalls: []

    # Broker
#    Rector\NodeTypeResolver\Broker\BrokerFactory: ~
#    PHPStan\Broker\Broker:
#        factory: ['@Rector\NodeTypeResolver\Broker\BrokerFactory', 'create']

    # required by Broker
    # this causes circular referene issue
#    PHPStan\Reflection\Php\PhpClassReflectionExtension:
#        calls:
#            # prevents circular reference
#            - ['setBroker', ['@PHPStan\Broker\Broker']]

#    PHPStan\Parser\FunctionCallStatementFinder: ~
#
#    Rector\NodeTypeResolver\NodeTypeResolver:
#        calls:
#            # prevents circular reference
#            - ['setBroker', ['@PHPStan\Broker\Broker']]
#
#    Rector\NodeTypeResolver\Reflection\Php\PhpMethodReflectionFactory:
#        calls:
#            # prevents circular reference
#            - ['setBroker', ['@PHPStan\Broker\Broker']]
#
#    # Parser
#    PHPStan\Parser\DirectParser: ~
#    PHPStan\Parser\CachedParser:
#        arguments:
#            - '@PHPStan\Parser\DirectParser'
#
#    # prefered service for interface
#    PHPStan\Parser\Parser:
#        alias: PHPStan\Parser\CachedParser
#
#    PHPStan\Cache\Cache: ~
#    PHPStan\Cache\MemoryCacheStorage: ~
#    PHPStan\File\FileHelper:
#        arguments:
#            $workingDirectory: %kernel.root_dir%/../../
#
#    # required for Broker
#    PHPStan\Type\FileTypeMapper: ~
