parameters:
    # todo
    kernel_class: # for name based service refactoring

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # PSR-4 autodiscovery
    Rector\:
        resource: '../../src'

    # autowire by interface
    Rector\Contract\Parser\ParserInterface:
        alias: Rector\Parser\Parser

    # 3rd party services
    Symfony\Component\Console\Application:
        arguments:
            $name: "Rector"

    # PhpParser - Parser
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']
    PhpParser\ParserFactory: ~
    PhpParser\BuilderFactory: ~

    PhpParser\NodeVisitor\NameResolver: ~
    PhpParser\NodeTraverser: ~

    # PhpParser - Printer
    PhpParser\PrettyPrinter\Standard: ~
