imports:
  - { resource: '../../packages/TriggerExtractor/src/config/services.yml' }

parameters:
    # todo
    kernel_class: # for name based service refactoring

    name: "Rector"

services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Rector\:
        resource: '../../src'
        exclude: '../../src/{Node/Attribute.php}'

    # autowire by interface
    Rector\Contract\Parser\ParserInterface:
        alias: Rector\Parser\Parser

    Rector\NodeTraverser\StandaloneTraverseNodeTraverser:
        calls:
            - ['addNodeVisitor', ['@PhpParser\NodeVisitor\NameResolver']]
            - ['addNodeVisitor', ['@Rector\NodeVisitor\NodeConnector']]
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\TypeResolver']]
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\ClassResolver']]

    # 3rd party services
    Symfony\Component\Console\Application:
        arguments:
            $name: "%name%"

    # PhpParser - Parser
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']
    PhpParser\ParserFactory: ~
    PhpParser\BuilderFactory: ~

    PhpParser\NodeVisitor\CloningVisitor:
    PhpParser\NodeVisitor\NameResolver:
        arguments:
            $options:
                'replaceNodes': false

    PhpParser\NodeTraverser: ~

    # PhpParser - Printer
    PhpParser\PrettyPrinter\Standard: ~
