services:
    _defaults:
        autowire: true

    Rector\:
        resource: '../../src'
        exclude: '../../src/{Node/Attribute.php,Rector/Contrib,Rector/Dynamic,Rector/MagicDisclosure}'

    # autowire by interface
    Rector\Contract\Parser\ParserInterface:
        alias: Rector\Parser\Parser

    Rector\NodeTraverser\StandaloneTraverseNodeTraverser:
        calls:
            # adds FQN names for elements
            - ['addNodeVisitor', ['@PhpParser\NodeVisitor\NameResolver']]
            # adds previous, next and parent node via attribute
            - ['addNodeVisitor', ['@Rector\NodeVisitor\NodeConnector']]
            # adds current class to all nodes via attribute
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\ClassResolver']]
            # adds current method to all nodes via attribute
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\MethodResolver']]
            # adds type to variable and property nodes via attribute
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\TypeResolver']]
            # adds current namespace to all nodes via attribute
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\NamespaceResolver']]
            # adds class/interface/function/method scope to all nodes attribute
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\ScopeResolver']]

    # PhpParser - Parser
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']
    PhpParser\ParserFactory: ~
    PhpParser\BuilderFactory: ~

    PhpParser\NodeVisitor\CloningVisitor:
    PhpParser\NodeVisitor\NameResolver:
        arguments:
            $options:
                # keep nodes the same, so the code can be saved without name changes
                'replaceNodes': false

    PhpParser\NodeTraverser: ~

    # PhpParser - Printer
    PhpParser\PrettyPrinter\Standard: ~

    # Symfony\Console
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
