parameters:
    # todo
    kernel_class: # for name based service refactoring

services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Rector\:
        resource: '../../src'

    # 3rd party services
    Symfony\Component\Console\Application:
        arguments:
            $name: "Rector"
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']
    PhpParser\BuilderFactory: ~

    PhpParser\NodeTraverser: ~

    # Traverser
    PhpParser\ParserFactory: ~
    # Printer
    PhpParser\PrettyPrinter\Standard: ~
