rectors:
    Rector\Rector\Contrib\PHPUnit\ExceptionRector: ~
    Rector\Rector\Contrib\PHPUnit\GetMockRector: ~

    # ref. https://github.com/sebastianbergmann/phpunit/compare/5.7.9...6.0.0
    Rector\Rector\Dynamic\PseudoNamespaceToNamespaceRector:
        - 'PHPUnit_'
