services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Rector\TriggerExtractor\:
        resource: '../../src'
        exclude: '../../src/{Deprecation/ClassMethodDeprecation.php}'
