services:
    _defaults:
        autowire: true

    Rector\ReflectionDocBlock\:
        resource: '../../src'

    phpDocumentor\Reflection\DocBlockFactory: ~
    phpDocumentor\Reflection\DocBlock\StandardTagFactory: ~
    phpDocumentor\Reflection\DocBlock\DescriptionFactory: ~
    phpDocumentor\Reflection\TypeResolver: ~

    phpDocumentor\Reflection\Types\ContextFactory: ~
    phpDocumentor\Reflection\FqsenResolver: ~
