rectors:
    Rector\Rector\Contrib\Symfony\Form\FormTypeGetParentRector: ~

    Rector\Rector\Dynamic\ClassConstantReplacerRector:
        # form
        'Symfony\Component\Form\FormEvents':
            'PRE_BIND': 'PRE_SUBMIT'
            'BIND': 'SUBMIT'
            'POST_BIND': 'POST_SUBMIT'

    Rector\Rector\Dynamic\MethodNameReplacerRector:
        # form
        'Symfony\Component\Form\AbstractType':
            'setDefaultOptions': 'configureOptions'
        'Symfony\Component\Form\FormTypeInterface':
            'getName': 'getBlockPrefix'
        # property access
        Symfony\Component\PropertyAccess\PropertyAccess:
            'getPropertyAccessor': 'createPropertyAccessor'

    Rector\Rector\Dynamic\ClassReplacerRector:
        # form
        'Symfony\Component\Form\Util\VirtualFormAwareIterator': 'Symfony\Component\Form\Util\InheritDataAwareIterator'
