rectors:
    - Rector\Rector\Contrib\Symfony\ConstraintUrlOptionRector
    - Rector\Rector\Contrib\Symfony\ConstraintValidatorTestClassRenameRector
    - Rector\Rector\Contrib\Symfony\FormIsValidRector
    - Rector\Rector\Contrib\Symfony\FrameworkBundleClassReplacementsRector
    - Rector\Rector\Contrib\Symfony\StringFormTypeToClassRector
    - Rector\Rector\Contrib\Symfony\VarDumperTestTraitMethodArgsRector
    - Rector\Rector\Contrib\Symfony\ContainerBuilderCompileEnvArgumentRector
    - Rector\Rector\Contrib\Symfony\CompilerAddPassPriorityRector
