rectors:
    # dependency-injection
    Rector\Rector\Dynamic\MethodArgumentChangerRector:
        -
            class: Symfony\Component\DependencyInjection\ContainerBuilder
            method: addCompilerPass
            position: 3
            type: added
            default_value: 0
